apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: end-to-end-devops-project
  namespace: argocd
spec:
  generators:
    # One Application for every folder under end-to-end-devops-project/ (dev, qa, prd)
    - git:
        repoURL: https://github.com/sbaransi/end-to-end-devops-gitops.git
        revision: main
        directories:
          - path: end-to-end-devops-project/*

  template:
    metadata:
      name: '{{path.basename}}-flask-app'
      namespace: argocd

    spec:
      project: default

      source:
        repoURL: https://github.com/sbaransi/end-to-end-devops-gitops.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
